/**
 * *****************************************************************************
 * Copyright (c) 2015, Thomas.H Warner. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE. 
 ******************************************************************************
 */
package fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.components.gamehistory;

import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.components.Console3D;
import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.components.gamehistory.GameHistoryList;
import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.dto.MoveQueue;
import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.opengl.utils.DataUtils;
import javax.swing.JFrame;

/**
 *
 * @author thw
 */
public class SaveGameDialog extends javax.swing.JDialog {
    
    /**
     * 
     */
    private MoveQueue queue;
    
    /**
     * Creates new form SaveGameDialog
     * @param parent
     * @param queue
     */
    public SaveGameDialog(final java.awt.Frame parent, final MoveQueue queue) {
        super(parent, true);
        this.queue = queue;
        initComponents();
        this.saveGameFenValueTextField.setText(this.queue.getFen() == null ? "?" : this.queue.getFen());
        this.setLocationRelativeTo(null);
        this.saveGameDescriptionTextField.requestFocus();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveGameDescriptionLabel = new javax.swing.JLabel();
        saveGameDescriptionTextField = new javax.swing.JTextField();
        saveGameNowButton = new javax.swing.JButton();
        saveGameCancelButton = new javax.swing.JButton();
        saveGameDialogLabel = new javax.swing.JLabel();
        saveGameFenValueLabel = new javax.swing.JLabel();
        saveGameFenValueTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setResizable(false);

        saveGameDescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveGameDescriptionLabel.setText("Game description :");

        saveGameDescriptionTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveGameDescriptionTextField.setDoubleBuffered(true);
        saveGameDescriptionTextField.setSelectionColor(new java.awt.Color(100, 100, 100));

        saveGameNowButton.setText("Save game now !");
        saveGameNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameNowButtonActionPerformed(evt);
            }
        });

        saveGameCancelButton.setText("Cancel");
        saveGameCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameCancelButtonActionPerformed(evt);
            }
        });

        saveGameDialogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveGameDialogLabel.setText("To save chess game's configuration, enter a description.");

        saveGameFenValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveGameFenValueLabel.setText("Game's FEN value :");

        saveGameFenValueTextField.setEditable(false);
        saveGameFenValueTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveGameFenValueTextField.setSelectionColor(new java.awt.Color(100, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(saveGameDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(saveGameFenValueLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(saveGameFenValueTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveGameDialogLabel)
                                .addGap(0, 93, Short.MAX_VALUE))
                            .addComponent(saveGameDescriptionTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveGameCancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveGameNowButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(saveGameDialogLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveGameDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveGameDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveGameFenValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveGameFenValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveGameNowButton)
                    .addComponent(saveGameCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveGameNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameNowButtonActionPerformed
        // Save game event :
        final String description = this.saveGameDescriptionTextField.getText();
        this.setVisible(false);
        this.queue.setDescription(description == null || description.equals("") ? "?" : description);
        DataUtils.xmlSerializeMoveQueue(this.queue, this.saveGameDescriptionTextField.getText(), true);
       ((Console3D) this.getParent()).getSavedGamesScrollPane().setViewportView(null);
       ((Console3D) this.getParent()).getSavedGamesScrollPane().setViewportView(
               GameHistoryList.getNewInstance((JFrame) this.getParent()));
        this.dispose();
    }//GEN-LAST:event_saveGameNowButtonActionPerformed

    private void saveGameCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameCancelButtonActionPerformed
        // Cancel save event :
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_saveGameCancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveGameCancelButton;
    private javax.swing.JLabel saveGameDescriptionLabel;
    private javax.swing.JTextField saveGameDescriptionTextField;
    private javax.swing.JLabel saveGameDialogLabel;
    private javax.swing.JLabel saveGameFenValueLabel;
    private javax.swing.JTextField saveGameFenValueTextField;
    private javax.swing.JButton saveGameNowButton;
    // End of variables declaration//GEN-END:variables
}
