/**
 * *****************************************************************************
 * Copyright (c) 2015, Thomas.H Warner. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE. 
 ******************************************************************************
 */
package fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.components;

import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.chessui3d.opengl.constants.UI3DConst;
import fr.com.jellyfish.jfgjellyfishchess.jellyfishchess.jellyfish.interfaces.Writable;

/**
 *
 * @author thw
 */
public class ExitDialog extends javax.swing.JDialog {

    /**
     * Console instance reference.
     */
    private Writable console;
    
    /**
     * Creates new form ExitDialog
     * @param parent
     * @param console
     * @param title
     * @param text
     */
    public ExitDialog(final java.awt.Frame parent, final Writable console, final String title,
            final String text) {
        super(parent, true);
        this.console = console;
        initComponents();
        this.setTitle(title);
        this.exitDialogTextArea.setText(text);
        
        java.net.URL imgURL = getClass().getResource(UI3DConst.JELLYFISH_FRAME_ICON);
        javax.swing.ImageIcon img = new javax.swing.ImageIcon(imgURL);
        this.setIconImage(img.getImage());
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitDialogContainer = new javax.swing.JPanel();
        exitDialogCancelButton = new javax.swing.JButton();
        exitDialogExitButton = new javax.swing.JButton();
        textAreajScrollPane = new javax.swing.JScrollPane();
        exitDialogTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        exitDialogCancelButton.setText(" Cancel ");
        exitDialogCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDialogCancelButtonActionPerformed(evt);
            }
        });

        exitDialogExitButton.setText("Exit now !");
        exitDialogExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDialogExitButtonActionPerformed(evt);
            }
        });

        textAreajScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textAreajScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        exitDialogTextArea.setEditable(false);
        exitDialogTextArea.setColumns(20);
        exitDialogTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitDialogTextArea.setRows(5);
        exitDialogTextArea.setBorder(null);
        exitDialogTextArea.setDoubleBuffered(true);
        exitDialogTextArea.setFocusable(false);
        exitDialogTextArea.setOpaque(false);
        textAreajScrollPane.setViewportView(exitDialogTextArea);

        javax.swing.GroupLayout exitDialogContainerLayout = new javax.swing.GroupLayout(exitDialogContainer);
        exitDialogContainer.setLayout(exitDialogContainerLayout);
        exitDialogContainerLayout.setHorizontalGroup(
            exitDialogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exitDialogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exitDialogContainerLayout.createSequentialGroup()
                        .addGap(0, 162, Short.MAX_VALUE)
                        .addComponent(exitDialogExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitDialogCancelButton))
                    .addComponent(textAreajScrollPane))
                .addContainerGap())
        );
        exitDialogContainerLayout.setVerticalGroup(
            exitDialogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitDialogContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textAreajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(exitDialogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitDialogCancelButton)
                    .addComponent(exitDialogExitButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitDialogContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitDialogContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitDialogExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDialogExitButtonActionPerformed
        this.console.exit();
    }//GEN-LAST:event_exitDialogExitButtonActionPerformed

    private void exitDialogCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDialogCancelButtonActionPerformed
        this.setVisible(false);
        this.console = null;
        this.dispose();
    }//GEN-LAST:event_exitDialogCancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitDialogCancelButton;
    private javax.swing.JPanel exitDialogContainer;
    private javax.swing.JButton exitDialogExitButton;
    private javax.swing.JTextArea exitDialogTextArea;
    private javax.swing.JScrollPane textAreajScrollPane;
    // End of variables declaration//GEN-END:variables
}
